#ifndef LIBMARY__LIBMARY_CONFIG__H__
#define LIBMARY__LIBMARY_CONFIG__H__

#undef LIBMARY_GLIB
#define LIBMARY_PTHREAD 1

#define LIBMARY_MT_SAFE 1

#define LIBMARY_ENABLE_EPOLL 1
#undef LIBMARY_ENABLE_KQUEUE

#undef LIBMARY_WIN32_IOCP
#undef LIBMARY_USE_SELECT
#undef LIBMARY_USE_POLL

#define LIBMARY_PLATFORM_DEFAULT 1
#undef LIBMARY_PLATFORM_ANDROID
#undef LIBMARY_PLATFORM_FREEBSD
#undef LIBMARY_PLATFORM_MACOSX
#undef LIBMARY_PLATFORM_WIN32
#undef LIBMARY_PLATFORM_CYGWIN

#undef LIBMARY_ENABLE_MWRITEV

#undef LIBMARY_WIN32_SECURE_CRT

#define LIBMARY_NO_EXCEPTIONS 1

#endif /* LIBMARY__LIBMARY_CONFIG__H__ */

