#ifndef LIBMOMENT__LIBMOMENT_CONFIG__H__
#define LIBMOMENT__LIBMOMENT_CONFIG__H__

#undef MOMENT_GSTREAMER
#undef MOMENT_NETTLE
#undef MOMENT_CTEMPLATE
#undef MOMENT_GPERFTOOLS

#endif /* LIBMOMENT__LIBMOMENT_CONFIG__H__ */

